version: "3"

services:
  interface:
    build:
      context: "."
      dockerfile: "./dockerfiles/interface/Dockerfile"
    ports:
      - "3004:80"
    depends_on:
      - backend
      - client

  database:
    build:
      context: "."
      dockerfile: "./dockerfiles/database/Dockerfile"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  backend:
    build:
      context: "."
      dockerfile: "./dockerfiles/server/Dockerfile"
    command: sh -c "/wait && ./run"
    depends_on:
      - database
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=20

  client:
    build:
      context: "."
      dockerfile: "./dockerfiles/client/Dockerfile"
