// Code generated by protoc-gen-go. DO NOT EDIT.
// source: suborder.proto

package protoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubOrder_State int32

const (
	SubOrder_Pending   SubOrder_State = 0
	SubOrder_Completed SubOrder_State = 1
	SubOrder_Rejected  SubOrder_State = 2
	SubOrder_Issue     SubOrder_State = 3
)

var SubOrder_State_name = map[int32]string{
	0: "Pending",
	1: "Completed",
	2: "Rejected",
	3: "Issue",
}

var SubOrder_State_value = map[string]int32{
	"Pending":   0,
	"Completed": 1,
	"Rejected":  2,
	"Issue":     3,
}

func (x SubOrder_State) String() string {
	return proto.EnumName(SubOrder_State_name, int32(x))
}

func (SubOrder_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_280b26083f6725f3, []int{0, 0}
}

type SubOrder struct {
	SubOrderId           string               `protobuf:"bytes,1,opt,name=sub_order_id,json=subOrderId,proto3" json:"sub_order_id,omitempty"`
	OrderId              string               `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	State                SubOrder_State       `protobuf:"varint,3,opt,name=state,proto3,enum=SubOrder_State" json:"state,omitempty"`
	Bet                  uint64               `protobuf:"varint,4,opt,name=bet,proto3" json:"bet,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubOrder) Reset()         { *m = SubOrder{} }
func (m *SubOrder) String() string { return proto.CompactTextString(m) }
func (*SubOrder) ProtoMessage()    {}
func (*SubOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_280b26083f6725f3, []int{0}
}

func (m *SubOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubOrder.Unmarshal(m, b)
}
func (m *SubOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubOrder.Marshal(b, m, deterministic)
}
func (m *SubOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubOrder.Merge(m, src)
}
func (m *SubOrder) XXX_Size() int {
	return xxx_messageInfo_SubOrder.Size(m)
}
func (m *SubOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SubOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SubOrder proto.InternalMessageInfo

func (m *SubOrder) GetSubOrderId() string {
	if m != nil {
		return m.SubOrderId
	}
	return ""
}

func (m *SubOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SubOrder) GetState() SubOrder_State {
	if m != nil {
		return m.State
	}
	return SubOrder_Pending
}

func (m *SubOrder) GetBet() uint64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *SubOrder) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SubOrder) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *SubOrder) GetCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("SubOrder_State", SubOrder_State_name, SubOrder_State_value)
	proto.RegisterType((*SubOrder)(nil), "SubOrder")
}

func init() { proto.RegisterFile("suborder.proto", fileDescriptor_280b26083f6725f3) }

var fileDescriptor_280b26083f6725f3 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xb1, 0x6e, 0x83, 0x30,
	0x14, 0x45, 0xeb, 0x24, 0x04, 0x78, 0xd0, 0x14, 0x79, 0xa2, 0x59, 0x8a, 0x22, 0x55, 0x62, 0x72,
	0xa4, 0x74, 0xaa, 0xd4, 0x0e, 0xa8, 0x53, 0xa6, 0x56, 0xa4, 0x3b, 0xc2, 0xf8, 0x15, 0x51, 0x85,
	0x18, 0x61, 0xfb, 0xcb, 0xfb, 0x03, 0x15, 0x06, 0xb2, 0x66, 0xe3, 0x71, 0xcf, 0xb9, 0xba, 0x86,
	0x8d, 0x32, 0x5c, 0xf6, 0x02, 0x7b, 0xd6, 0xf5, 0x52, 0xcb, 0xed, 0x53, 0x2d, 0x65, 0x7d, 0xc6,
	0xbd, 0xbd, 0xb8, 0xf9, 0xd9, 0xeb, 0xa6, 0x45, 0xa5, 0xcb, 0xb6, 0x1b, 0x81, 0xdd, 0xdf, 0x02,
	0xbc, 0x93, 0xe1, 0x9f, 0x83, 0x43, 0x13, 0x08, 0x95, 0xe1, 0x85, 0x2d, 0x28, 0x1a, 0x11, 0x93,
	0x84, 0xa4, 0x7e, 0x0e, 0x6a, 0xca, 0x8f, 0x82, 0x3e, 0x82, 0x77, 0x4d, 0x17, 0x36, 0x75, 0xe5,
	0x14, 0x3d, 0x83, 0xa3, 0x74, 0xa9, 0x31, 0x5e, 0x26, 0x24, 0xdd, 0x1c, 0x1e, 0xd8, 0x5c, 0xcb,
	0x4e, 0xc3, 0xef, 0x7c, 0x4c, 0x69, 0x04, 0x4b, 0x8e, 0x3a, 0x5e, 0x25, 0x24, 0x5d, 0xe5, 0xc3,
	0x27, 0x7d, 0x05, 0xa8, 0x7a, 0x2c, 0x35, 0x8a, 0xa2, 0xd4, 0xb1, 0x93, 0x90, 0x34, 0x38, 0x6c,
	0xd9, 0x38, 0x9c, 0xcd, 0xc3, 0xd9, 0xf7, 0x3c, 0x3c, 0xf7, 0x27, 0x3a, 0xb3, 0xaa, 0xe9, 0xc4,
	0xac, 0xae, 0x6f, 0xab, 0x13, 0x9d, 0x69, 0xfa, 0x0e, 0x61, 0x25, 0xdb, 0xee, 0x8c, 0x93, 0xec,
	0xde, 0x94, 0x83, 0x2b, 0x9f, 0xe9, 0xdd, 0x1b, 0x38, 0xf6, 0x59, 0x34, 0x00, 0xf7, 0x0b, 0x2f,
	0xa2, 0xb9, 0xd4, 0xd1, 0x1d, 0xbd, 0x07, 0xff, 0x63, 0x86, 0x22, 0x42, 0x43, 0xf0, 0x72, 0xfc,
	0xc5, 0x6a, 0xb8, 0x16, 0xd4, 0x07, 0xe7, 0xa8, 0x94, 0xc1, 0x68, 0xc9, 0xd7, 0xb6, 0xfe, 0xe5,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x77, 0xdb, 0xec, 0xb3, 0xaf, 0x01, 0x00, 0x00,
}
