FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/conf.d /etc/nginx/conf.d
COPY ./nginx/include.d /etc/nginx/include.d
COPY ./nginx/sites-enabled.d/interface.conf /etc/nginx/sites-enabled.d/interface.conf